<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="UTF-8"/>

<xsl:template match="/">

<HTML dir="rtl">
<HEAD>
<SCRIPT LANGUAGE="JavaScript" SRC="tree.js"></SCRIPT>
  <SCRIPT LANGUAGE="JavaScript" SRC="../SearchPath.js"></SCRIPT>
  <SCRIPT LANGUAGE="JavaScript1.2" SRC="cookutil.js"></SCRIPT>
  <LINK REL="stylesheet" HREF="LinkWare1.css" TYPE="text/css" />
  <TITLE>דף הקטלוג <xsl:value-of select="TreeIndex/CatalogName" /></TITLE>

<style type="text/css">
	html, body {
	margin: 0;
	padding: 0;
	background: #f4f7fb;
	color: #13213c;
	font-family: "Segoe UI", Arial, sans-serif;
	}
	.BodyIndex {
	margin: 0 !important;
	padding: 14px !important;
	box-sizing: border-box;
	background: #f4f7fb !important;
	font-family: "Segoe UI", Arial, sans-serif !important;
	}

	/* Catalog title */
	.index-header {
	width: 100%;
	min-height: 58px;
	box-sizing: border-box;
	display: flex;
	align-items: center;
	justify-content: space-between;
	direction: rtl;
	padding: 0 18px;
	margin-bottom: 14px;
	color: #fff;
	background: linear-gradient(to bottom, #185aa8, #0d4385);
	border: 1px solid #0b3971;
	border-radius: 10px;
	box-shadow: 0 3px 12px rgba(20,48,85,.14);

	/* חדש */
	position: sticky;
	top: 0;
	z-index: 1000;
	}
	.index-title-wrap {
	display: flex;
	align-items: center;
	gap: 11px;
	}
	.index-title-icon {
	width: 34px;
	height: 34px;
	border-radius: 8px;
	display: inline-flex;
	align-items: center;
	justify-content: center;
	background: rgba(255,255,255,.14);
	font-size: 20px;
	}
	.index-title-label {
	color: #cfe3fb;
	font-size: 11px;
	font-weight: 600;
	margin-bottom: 2px;
	}
	.index-title {
	color: #fff;
	font-size: 20px;
	font-weight: 700;
	line-height: 1.15;
	}
	.index-subtitle {
	color: #d9e9fb;
	font-size: 12px;
	font-weight: 500;
	}

	/* Legacy tree table generated by tree.js */
	.BodyIndex table:not(.index-header-table) {
	border-collapse: separate;
	border-spacing: 10px 0;
	}
	.BodyIndex table:not(.index-header-table) td {
	vertical-align: top;
	}

	/* Tree items */
	.level1, .level2, .level3, .level4, .level5 {
	display: inline-block;
	box-sizing: border-box;
	font-family: "Segoe UI", Arial, sans-serif !important;
	color: #183b66 !important;
	line-height: 1.45;
	border-radius: 6px;
	transition: background-color .12s ease, color .12s ease;
	}
	.level1 { font-size: 14px !important; font-weight: 700 !important; }
	.level2 { font-size: 13px !important; font-weight: 600 !important; }
	.level3, .level4, .level5 { font-size: 12px !important; font-weight: 500 !important; }

	.level1 a, .level2 a, .level3 a, .level4 a, .level5 a {
	color: #174f8f !important;
	text-decoration: none !important;
	font-family: "Segoe UI", Arial, sans-serif !important;
	}
	.level1 a:hover, .level2 a:hover, .level3 a:hover,
	.level4 a:hover, .level5 a:hover {
	color: #0d4385 !important;
	text-decoration: underline !important;
	}

	/* Each legacy row/div */
	.BodyIndex div[style*="right="] {
	min-height: 31px;
	display: flex;
	align-items: center;
	flex-direction: row;
	gap: 7px;
	box-sizing: border-box;
	padding: 4px 8px;
	margin: 2px 0;
	background: #fff;
	border: 1px solid #e0e8f1;
	border-radius: 7px;
	}
	.BodyIndex div[style*="right="]:hover {
	background: #eef5ff;
	border-color: #c7d9ee;
	}

	/* Existing folder/page/item GIFs */
	.BodyIndex div[style*="right="] > img {
	width: 18px;
	height: 18px;
	object-fit: contain;
	cursor: pointer;
	flex: 0 0 auto;
	}

	/* Nested levels get a subtle visual hierarchy */
	.BodyIndex div[style*="right=40"] { background: #fbfcfe; }
	.BodyIndex div[style*="right=60"],
	.BodyIndex div[style*="right=80"],
	.BodyIndex div[style*="right=100"] { background: #fcfdff; }

	/* Hide the old decorative underline spacing */
	.underLine {
	border: 0 !important;
	height: 0 !important;
	margin: 0 !important;
	padding: 0 !important;
	}
	.underLine br { display: none; }

	/* Scrollbar */
	body::-webkit-scrollbar { width: 10px; height: 10px; }
	body::-webkit-scrollbar-track { background: #eef3f8; }
	body::-webkit-scrollbar-thumb {
	background: #b9c9dc;
	border-radius: 10px;
	border: 2px solid #eef3f8;
	}
	body::-webkit-scrollbar-thumb:hover { background: #91aac6; }

	/* ===== RTL tree hierarchy ===== */
	html, body, .BodyIndex {
	direction: rtl !important;
	text-align: right !important;
	}

	/* The legacy XSL outputs text before the image.
	order:-1 makes the icon the first/right-most element. */
	.BodyIndex div[style*="right="] {
	direction: rtl !important;
	text-align: right !important;
	flex-direction: row !important;
	justify-content: flex-start !important;
	width: auto !important;
	}

	.BodyIndex div[style*="right="] > img {
	order: -1 !important;
	margin: 0 0 0 5px !important;
	}

	/* Clear visual hierarchy: 24px indentation for every nested level */
	.BodyIndex div[style*="right=20"] {
	margin-right: 0 !important;
	}
	.BodyIndex div[style*="right=40"] {
	margin-right: 24px !important;
	}
	.BodyIndex div[style*="right=60"] {
	margin-right: 48px !important;
	}
	.BodyIndex div[style*="right=80"] {
	margin-right: 72px !important;
	}
	.BodyIndex div[style*="right=100"] {
	margin-right: 96px !important;
	}

	/* Nested levels: subtle hierarchy guide */
	.BodyIndex div[style*="right=40"],
	.BodyIndex div[style*="right=60"],
	.BodyIndex div[style*="right=80"],
	.BodyIndex div[style*="right=100"] {
	border-right: 2px solid #d6e3f2 !important;
	padding-right: 10px !important;
	}

	/* Make modern PNG tree icons crisp and slightly larger */
	.BodyIndex div[style*="right="] > img {
	width: 20px !important;
	height: 20px !important;
	}
	.catalog-search {
	display: flex;
	align-items: center;
	direction: rtl;
	}

	.catalog-search-box {
	height: 34px;
	display: flex;
	align-items: center;
	gap: 4px;
	padding: 0 6px;
	background: #fff;
	border-radius: 7px;
	border: 1px solid rgba(255,255,255,.35);
	box-shadow: 0 1px 4px rgba(0,0,0,.12);
	direction: rtl;
	}

	.catalog-search-box input {
	width: 190px;
	height: 28px;
	border: 0;
	outline: 0;
	font-family: "Segoe UI", Arial, sans-serif;
	font-size: 13px;
	color: #183b66;
	background: transparent;
	direction: rtl;
	}

	.catalog-search-box button {
	width: 27px;
	height: 27px;
	padding: 0;
	border: 0;
	border-radius: 4px;
	background: transparent;
	color: #31577e;
	cursor: pointer;
	font-size: 13px;
	}

	.catalog-search-box button:hover {
	background: #e8f1fb;
	}

	#catalogSearchCount {
	min-width: 38px;
	text-align: center;
	direction: ltr;
	font-size: 11px;
	color: #52677e;
	}

	/* כל התוצאות */
	.catalog-search-match {
	background: #fff29a !important;
	border-radius: 3px;
	}

	/* התוצאה הפעילה */
	.catalog-search-current {
	background: #ffb52e !important;
	box-shadow: 0 0 0 2px rgba(255,181,46,.25);
	}
</style>
	<script type="text/javascript">
		<![CDATA[

var catalogSearchResults = [];
var catalogSearchIndex = -1;


function catalogSearchKeyUp(e) {

    if (e && e.keyCode == 13) {
        catalogSearchNext();
        return;
    }

    if (e && e.keyCode == 27) {
        clearCatalogSearch();
        return;
    }

    runCatalogSearch();
}


function runCatalogSearch() {

    clearCatalogSearchMarks();

    var input = document.getElementById('catalogSearch');
    if (!input) return;

    var searchText = trimText(input.value).toLowerCase();

    if (searchText == '') {
        updateCatalogSearchCount();
        return;
    }

    var spans = document.querySelectorAll(
        '.level1, .level2, .level3, .level4, .level5'
    );

    for (var i = 0; i < spans.length; i++) {

        var text = getElementText(spans[i]).toLowerCase();

        if (text.indexOf(searchText) >= 0) {

            catalogSearchResults.push(spans[i]);

            spans[i].className += ' catalog-search-match';
        }
    }

    if (catalogSearchResults.length > 0) {

        catalogSearchIndex = 0;

        showCatalogSearchResult();
    }

    updateCatalogSearchCount();
}


function catalogSearchNext() {

    if (catalogSearchResults.length == 0) {
        runCatalogSearch();
        return;
    }

    catalogSearchIndex++;

    if (catalogSearchIndex >= catalogSearchResults.length)
        catalogSearchIndex = 0;

    showCatalogSearchResult();
}


function catalogSearchPrev() {

    if (catalogSearchResults.length == 0) {
        runCatalogSearch();
        return;
    }

    catalogSearchIndex--;

    if (catalogSearchIndex < 0)
        catalogSearchIndex = catalogSearchResults.length - 1;

    showCatalogSearchResult();
}


function showCatalogSearchResult() {

    if (catalogSearchResults.length == 0)
        return;

    for (var i = 0; i < catalogSearchResults.length; i++) {
        removeClass(catalogSearchResults[i], 'catalog-search-current');
    }

    var element = catalogSearchResults[catalogSearchIndex];

    openSearchParents(element);

    if (element.className.indexOf('catalog-search-current') < 0)
        element.className += ' catalog-search-current';

    try {
        element.scrollIntoView({
            behavior: 'smooth',
            block: 'center'
        });
    }
    catch (e) {
        element.scrollIntoView();
    }

    updateCatalogSearchCount();
}


function openSearchParents(element) {

    var parent = element.parentNode;

    while (parent && parent != document.body) {

        if (parent.id &&
            parent.id.indexOf('inner_') == 0 &&
            parent.style.display == 'none') {

            parent.style.display = '';
        }

        parent = parent.parentNode;
    }
}


function clearCatalogSearchMarks() {

    for (var i = 0; i < catalogSearchResults.length; i++) {

        removeClass(
            catalogSearchResults[i],
            'catalog-search-match'
        );

        removeClass(
            catalogSearchResults[i],
            'catalog-search-current'
        );
    }

    catalogSearchResults = [];
    catalogSearchIndex = -1;
}


function clearCatalogSearch() {

    clearCatalogSearchMarks();

    var input = document.getElementById('catalogSearch');

    if (input) {
        input.value = '';
        input.focus();
    }

    updateCatalogSearchCount();
}


function updateCatalogSearchCount() {

    var count = document.getElementById('catalogSearchCount');

    if (!count)
        return;

    if (catalogSearchResults.length == 0) {
        count.innerHTML = '';
        return;
    }

    count.innerHTML =
        (catalogSearchIndex + 1) +
        '/' +
        catalogSearchResults.length;
}


function removeClass(element, className) {

    var reg =
        new RegExp('(^|\\s)' + className + '(\\s|$)', 'g');

    element.className =
        element.className.replace(reg, ' ');
}


function getElementText(element) {

    if (typeof element.textContent != 'undefined')
        return element.textContent;

    return element.innerText || '';
}


function trimText(text) {
    return text.replace(/^\s+|\s+$/g, '');
}

]]>
	</script>
</HEAD>
<BODY class="BodyIndex"  dir="rtl" onload="JavaScript:preloadImages()" onunload="JavaScript:addToCookieDiv()">

<input type="hidden" name="temp" value="0"/>
<script language="JavaScript">
	 var ExpandDiv =  new Array();
 	 var ExpandDivStyle =  new Array();
 //alert(ExpndDiv.length);
</script>

	<xsl:choose>
		<xsl:when test="//IsWebEditor = 'True'">
			<script language="JavaScript">
			<![CDATA[
				var siteLocation;
				var catalogNumber;
				var LinesPerCol;

				var temp = document.getElementsByName('temp')[0];
				temp.value = -1;

				LinesPerCol = 24;
				catalogNumber = ']]><xsl:value-of select="//TreeIndex/CatalogKey"/><![CDATA[';
	  	    ]]>
			</script>
		</xsl:when>
		<xsl:otherwise>
			<script type="text/javascript">
			<![CDATA[
				var siteLocation;
				var catalogNumber;
				var LinesPerCol;

				document.getElementsByName('temp')[0].value = -1;
				LinesPerCol = 20;
				siteLocation = document.location.href;
				siteLocation = siteLocation.toUpperCase()
				siteLocation = siteLocation.split("CATALOGS/");    //Put here the Directory site of the catalog.
				siteLocation = siteLocation[1].split("/");
				catalogNumber = siteLocation[0];
				//alert(catalogNumber);
	  	    ]]>
			</script>
		</xsl:otherwise>
	</xsl:choose>

<script LANGUAGE="JavaScript">
function newImage(arg) {
	if (document.images) {
		rslt = new Image();
		rslt.src = arg;
		return rslt;
	}
}

function changeImages() {
 if (document.images)
 	{
 		if (preloadFlag == true)
 			{
   				// Must Be Open And Close Images.
   				// The Files will be xxxxOpen.jpg and xxxxClose.jpg      xxxxx = Object ObjectClass
   				
   				NewPictureName = document[changeImages.arguments[0]].src;
   				if (NewPictureName.indexOf("Close") == -1)
   					{
   						NewPictureName = NewPictureName.replace("Open","Close");
   						//alert(NewPictureName);
   					}
   				else
   					{
   						NewPictureName = NewPictureName.replace("Close","Open");
   						//alert(NewPictureName);
   					}
   				document[changeImages.arguments[0]].src = NewPictureName;
   			}
 	}
}

var preloadFlag = false;
function preloadImages() {
	if (document.images) {
	
		//alert("run");
		chapterOpen = newImage("images/index/FolderOpen.png");
		chapterClose = newImage("images/index/FolderClose.png");
		//chapter_Without_Sun = newImage("Folder.jpg"); - not available.

		Page_Collapse = newImage("images/index/page_pic_plus.png");
		Page_Expand = newImage("images/index/page_pic_minus.png");
		Page_Without_Sun = newImage("images/index/page_pic.png");

		itemOpen = newImage("images/index/itemOpen.png");
		itemClose = newImage("images/index/itemClose.png");
		Item_Without_Sun = newImage("images/index/item.png");

		preloadFlag = true;
	}
	
	getFromCookieDiv()

}	
</script>

  <div align="right">

<div class="index-header">
    <div class="index-title-wrap">
        <div class="index-title-icon">&#9776;</div>
        <div>
            <div class="index-title-label">תוכן הקטלוג</div>
            <div class="index-title"><xsl:value-of select="TreeIndex/CatalogName" /></div>
        </div>
    </div>
	<div class="catalog-search">
		<div class="catalog-search-box">
			<input type="text"
				   id="catalogSearch"
				   placeholder="חיפוש בקטלוג..."
				   autocomplete="off"
				   onkeyup="catalogSearchKeyUp(event)" />

			<span id="catalogSearchCount"></span>

			<button type="button"
					onclick="catalogSearchPrev()"
					title="הקודם">&#9650;</button>

			<button type="button"
					onclick="catalogSearchNext()"
					title="הבא">&#9660;</button>

			<button type="button"
					onclick="clearCatalogSearch()"
					title="נקה">&#10005;</button>
		</div>
	</div>
</div>


	
	<script language ="javascript">insertTable()</script>
	<script language ="javascript">insertTR ()</script><script language ="javascript">insertTD()</script>

	<xsl:apply-templates select="TreeIndex/Object/Object" />
	</div>
	<div class="underLine"></div>
	<div id="NoneID"></div> <!-- This is id for uncollapse node. its for noneID in tree.js will not return error. -->
	</BODY>
	</HTML>
</xsl:template>

<xsl:template match="Object">

	<xsl:choose>
		<xsl:when test="Level = 1">
			<script language="javascript">
				var tempInput = document.getElementsByName('temp')[0];
				tempInput.value = (tempInput.value*1) + 1
				if ( ((tempInput.value*1)/LinesPerCol) == Math.round((tempInput.value*1)/LinesPerCol) ) {
					insertTD();				
				}
			</script>
			<xsl:choose>
				<xsl:when test="Object/Level > 1">
					<div  style="  right=20; cursor:hand;" >
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level1" dir="rtl"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level1" dir="rtl"><a target="_top"><xsl:attribute name="href">
							<xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose>
							</xsl:attribute><xsl:value-of select="Name" /></a></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/itemClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/itemClose.png','images/index/itemOpen.png');</xsl:attribute></img></xsl:when>
						</xsl:choose>&#160; &#160; &#160; &#160;  <!-- &nbsp; = &#160; -->
	     				</div>
					<DIV  style="display:none;"><xsl:attribute name="id">inner_<xsl:value-of select="ID" /></xsl:attribute>
					<xsl:apply-templates select="Object" />
					</DIV>
				</xsl:when>
				<xsl:otherwise>
					<div  style="  right=20;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level1" dir="rtl"><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level1" dir="rtl"><a target="_top"><xsl:attribute name="href">
							<xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose>
							</xsl:attribute>
							<xsl:value-of select="Name" /></a> - <xsl:value-of select="PageNum"  /></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
                            
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/item.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
					</xsl:choose>&#160; &#160; &#160; &#160;  <!-- &nbsp; = &#160; -->
	     				</div>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:when test="Level = 2">
			<xsl:choose>
				<xsl:when test="Object/Level > 2">
					<div  style="  right=40; cursor:hand;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level2" dir="rtl"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level2" dir="rtl"><a target="_top"><xsl:attribute name="href">
							<xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose>
							</xsl:attribute><xsl:value-of select="Name" /></a></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/itemClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/itemClose.png','images/index/itemOpen.png');</xsl:attribute></img></xsl:when>
						</xsl:choose>&#160; &#160; &#160; &#160;&#160; &#160; &#160; &#160;  <!-- &nbsp; = &#160; -->
	     				</div>
					<DIV  style="display:none;"><xsl:attribute name="id">inner_<xsl:value-of select="ID" /></xsl:attribute>
					<xsl:apply-templates select="Object" />
					</DIV>
				</xsl:when>
				<xsl:otherwise>
					<div  style="  right=40;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level2" dir="rtl"><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level2" dir="rtl"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a> - 
                <xsl:value-of select="PageNum"  />
              </span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/item.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
					</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;  <!-- &nbsp; = &#160; -->
	     				</div>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:when test="Level = 3">
			<xsl:choose>
				<xsl:when test="Object/Level > 3">
					<div  style="  right=60; cursor:hand;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level3" dir="rtl"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level3" dir="rtl"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/itemClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/itemClose.png','images/index/itemOpen.png');</xsl:attribute></img></xsl:when>
						</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;    <!-- &nbsp; = &#160; -->
	     				</div>
					<DIV  style="display:none;"><xsl:attribute name="id">inner_<xsl:value-of select="ID" /></xsl:attribute>
					<xsl:apply-templates select="Object" />
					</DIV>
				</xsl:when>
				<xsl:otherwise>
					<div  style="  right=60;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level3" dir="rtl"><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level3" dir="rtl"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a>
                <xsl:value-of select="PageNum"  />
              </span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/item.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
					</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;    <!-- &nbsp; = &#160; -->
	     				</div>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:when test="Level = 4">
			<xsl:choose>
				<xsl:when test="Object/Level > 4">
					<div  style="  right=80; cursor:hand;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level4"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level4"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/itemClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/itemClose.png','images/index/itemOpen.png');</xsl:attribute></img></xsl:when>
						</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;&#160;    <!-- &nbsp; = &#160; -->
	     				</div>
					<DIV  style="display:none;"><xsl:attribute name="id">inner_<xsl:value-of select="ID" /></xsl:attribute>
					<xsl:apply-templates select="Object" />
					</DIV>
				</xsl:when>
				<xsl:otherwise>
					<div  style="  right=80;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level4"><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level4"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a> - 
                <xsl:value-of select="PageNum"  />
              </span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/item.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
					</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;   <!-- &nbsp; = &#160; -->
	     				</div>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:when test="Level = 5">
			<xsl:choose>
				<xsl:when test="Object/Level > 5">
					<div  style="  right=100; cursor:hand;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level5"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level5"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/FolderClose.png','images/index/FolderOpen.png');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />');</xsl:attribute></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/itemClose.png" onmouseover="enter();" onmouseout="leave();"><xsl:attribute name="name"><xsl:value-of select="ID" /></xsl:attribute><xsl:attribute name="onclick">Switch('inner_<xsl:value-of select="ID" />','<xsl:value-of select="ID" />','images/index/itemClose.png','images/index/itemOpen.png');</xsl:attribute></img></xsl:when>
						</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;&#160; &#160; &#160; &#160;   <!-- &nbsp; = &#160; -->
	     				</div>
					<DIV  style="display:none;"><xsl:attribute name="id">inner_<xsl:value-of select="ID" /></xsl:attribute>
					<xsl:apply-templates select="Object" />
					</DIV>
				</xsl:when>
				<xsl:otherwise>
					<div  style="  right=100;">
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'">
							<span class="level5"><xsl:value-of select="Name" /></span>
			     			</xsl:when>
					     	<xsl:otherwise>
							<span class="level5"><a target="_top"><xsl:attribute name="href"><xsl:choose>
								<xsl:when test="//IsWebEditor = 'True'">ShowTemplate.aspx?Template=<xsl:value-of select="Template"/>&amp;Pkey=<xsl:value-of select="ID" />&amp;ParentKey=<xsl:value-of select="ParentKey"/>&amp;Type=2&amp;PkeyCatalog=<xsl:value-of select="//TreeIndex/CatalogKey"/></xsl:when>
								<xsl:otherwise><xsl:value-of select="ID" />.html</xsl:otherwise>
							</xsl:choose></xsl:attribute><xsl:value-of select="Name" /></a></span>
			     			</xsl:otherwise>
                        		</xsl:choose>
					<xsl:choose>
						<xsl:when test="ObjectClass = 'Folder'"><img src="images/index/FolderClose.png" onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Page'"><img src="images/index/page_pic.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
						<xsl:when test="ObjectClass = 'Item'"><img src="images/index/item.png"  onmouseover="enter();" onmouseout="leave();"></img></xsl:when>
					</xsl:choose>&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;&#160; &#160; &#160; &#160;  <!-- &nbsp; = &#160; -->
	     				</div>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
	</xsl:choose>
</xsl:template>
</xsl:stylesheet>